[package]
name = "dl-burning"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
burn = {version= "0.16.0", path = "../burn/crates/burn", features = ["train", "dataset", "vision", "candle-cuda"]}
rand = "0.9"
